---
- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: install the 'Development tools' package group
  yum:
    name: "@Development tools"
    state: latest

- name: install epel-release
  yum:
    name: epel-release
    state: latest

- name: install required packages
  yum:
    name:
      - vim
      - bind-utils
      - dkms
      - docker
    state: latest

- name: install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.20.1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: a+x

- name: enable docker service and start it
  systemd: 
    name: docker
    enabled: yes
    state: started

